name: mini_game
description: "一个小游戏项目"
publish_to: 'none'
version: 1.0.0+1 # 版本
author: "曹云友 <caoyunyou@foxmail.com>"
homepage: https://caoyunyou.github.io/

# 运行环境
environment:
  sdk: ^3.7.2

# 依赖
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  provider: ^6.1.5
  # 图标库
  cupertino_icons: ^1.0.8
  # 音频播放
  audioplayers: ^6.4.0
  # 日期格式化
  intl: ^0.19.0
  #  可以持久化存储在对应的机器上，即使关闭应用重新打开也能获取到
  shared_preferences: ^2.5.3
  #  sqlLite对应的工具，比较边界
  sqflite: ^2.4.2
  #  雪花算法ID生成工具
  snowflake_dart: ^2.0.0
  #  json注解
  json_annotation: ^4.9.0
  #  代码简化注解
  freezed_annotation: ^3.0.0
  # 进入动画
  flutter_native_splash: ^2.4.6
  #  状态管理+路由管理
  get: ^4.7.2
  # 页面加载
  flutter_easyloading: ^3.0.5

# 测试依赖
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  #  桌面图标
  flutter_launcher_icons: ^0.14.3


flutter:
  uses-material-design: true



  # 静态资源引入
  assets:
    - assets/images/
    - assets/audio/



  # 字体引入
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package

# 国际化配置
flutter_intl:
  enabled: true
  class_name: S
  main_locale: zh
  output_dir: lib/l10n/generated # 模板代码生成路径
  arb_dir: lib/l10n/arb # .arb 文件存放的路径